"""Enums and constants for the Zan.gov.kz API client."""

from enum import Enum


class Language(str, Enum):
    """Supported language codes for document retrieval."""

    RUS = "rus"
    KAZ = "kaz"


class ContentType(str, Enum):
    """Content element types found in documents."""

    DOC = "doc"
    TITLE = "title"
    SECTION = "section"
    ARTICLE = "article"
    HEADING = "heading"
    NOTE = "note"
    POINT = "point"
    SUBPOINT = "subpoint"
    TEXT = "text"
    SIDE_NOTE = "sideNote"
    SIDE_NOTE_GROUP = "sideNoteGroup"
    PRE = "pre"
    PREAMBLE = "preamble"
    SIGNATURE = "signature"
    WORK_POSITION = "workPosition"
    PERSON_NAME = "personName"
    TABLE_CELL = "tableCell"
    CHAPTER = "chapter"
    SUBSECTION = "subsection"
    TALE = "table"
    TABLE_ROW = "tableRow"
    ATTACH = "attach"
    SUBHEADING = "subheading"
    RCPI_NOTICE = "rcpi_notice"
    EXCLUDED = "excluded"
    TOC = "toc"
    PART = "part"
    TABLE_HEADER_ROW = "tableHeaderRow"
    PARAGRAPH = "paragraph"
    SUBATTACH = "subattach"
    IMAGE = "image"
    BUFFER = "buffer"
    DESCRIPTION = "description"


class ActTypeEnum(str, Enum):
    """Types of acts found in documents."""

    DOP = "ДОП"
    ZAK = "ЗАК"
    IZM = "ИЗМ"
    KZAK = "КЗАК"
    KONS = "КОНС"  # Конституция
    POR = "ПОР"
    POST = "ПОСТ"  # Постановление
    PRAV = "ПРАВ"
    PRIK = "ПРИК"
    RESH = "РЕШ"
    SOGL = "СОГЛ"
    UKAZ = "УКАЗ"
    NPOS = "НПОС"
    KOD = "КОД"
    MRP = "МРП"
    POL = "ПОЛ"
    PRCH = "ПРЧ"
    INST = "ИНСТ"
    DOG = "ДОГ"
    RAZ = "РАЗ"
    MET = "МЕТ"
    UST = "УСТ"
    UZAK = "УЗАК"
    UKZN = "УКЗН"
    UKON = "УКОН"
    NORM = "НОРМ"
    REGL = "РЕГЛ"
    PROT = "ПРОТ"
    RASP = "РАСП"
    KONV = "КОНВ"
    TREB = "ТРЕБ"
    PISM = "ПИСМ"
    STND = "СТНД"
    PLAN = "ПЛАН"
    OBRA = "ОБРА"
    PROG = "ПРОГ"
    MEMR = "МЕМР"
    KLAS = "КЛАС"
    NOM = "НОМ"
    SHEM = "СХЕМ"
    PROE = "ПРОЕ"
    OPIS = "ОПИС"
    DEKL = "ДЕКЛ"
    PRES = "ПРЕС"
    KONTS = "КОНЦ"
    USL = "УСЛ"
    KRIT = "КРИТ"
    STRA = "СТРА"
    KONT = "КОНТ"
    SUPR = "СУПР"
    OPOL = "ОПОЛ"
    POPR = "ПОПР"
    ZAYAV = "ЗАЯВ"
    HART = "ХАРТ"
    SNIP = "СНИП"
    PACT = "ПАКТ"
    KONK = "КОНК"
    SPRA = "СПРА"
    METU = "МЕТУ"
    METR = "МЕТР"
    OPRD = "ОПРД"
    TECHN = "ТЕХН"
    PRIZ = "ПРИЗ"
    RUK = "РУК"

    # trash
    MALFORMED_1 = "12262995"


class ActStatus(str, Enum):
    EXE = "exe"
    NEW = "new"
    YTS = "yts"  # lost its power
    TEMPORARY_REVOKED = "temporaryRevoked"
    UPD = "upd"
    BAK = "bak"
    VEXP = "vexp"
    STOP = "stop"
